"""add_spamblock

Revision ID: 33fa76b38840
Revises: 386af1e57996
Create Date: 2026-08-10 19:02:02.096027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33fa76b38840'
down_revision = '386af1e57996'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spam_restricted_until', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spam_restricted_until')
    # ### end Alembic commands ###