"""add blacklist table

Revision ID: 386af1e57996
Revises: f2b3a5046a1a
Create Date: 2026-08-08 13:55:37.405604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386af1e57996'
down_revision = 'f2b3a5046a1a'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_email', sa.String(), nullable=False),
    sa.Column('blocked_identifier', sa.String(), nullable=False),
    sa.Column('blocked_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['blocker_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_email', 'blocked_identifier', name='uq_blacklist')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist')
    # ### end Alembic commands ###