"""add_private_entities

Revision ID: 658fe93482c9
Revises: 5a31f4190443
Create Date: 2026-07-31 10:37:04.206073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658fe93482c9'
down_revision = '5a31f4190443'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'email', name='uq_join_request')
    )
    op.add_column('entities', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'is_private')
    op.drop_table('join_requests')
    # ### end Alembic commands ###